#ifndef HYTGRAPH_SEP_EXECUTION_DRIVER_HPP
#define HYTGRAPH_SEP_EXECUTION_DRIVER_HPP

#include <cstddef>

#include "sep_execution_config.hpp"
#include "sep_application.hpp"
#include "sep_execution_context.hpp"
#include "sep_execution_result.hpp"

namespace hytgraph::sep
{

    /**
     * Result of one logical SEP execution step.
     *
     * Phase 12 keeps this deliberately small. It provides enough information for
     * a future execution driver to report progress without exposing CUDA-specific
     * state to the rest of the project.
     */
    struct SEPExecutionStepResult
    {
        /**
         * Number of logical vertices considered by the execution step.
         *
         * For DD execution this may correspond to the current frontier/worklist.
         * For TD execution this may correspond to the topology traversal domain.
         */
        std::size_t vertices_processed{0};

        /**
         * Number of logical updates/messages generated by the step.
         */
        std::size_t updates_generated{0};

        /**
         * Whether the step produced any application-visible update.
         *
         * This is deliberately semantic rather than tied to a particular
         * activity/worklist representation.
         */
        bool changed{false};

        /**
         * Whether the application has reached its termination condition.
         *
         * The driver reports this value; the application remains responsible for
         * defining what constitutes convergence/termination.
         */
        bool converged{false};
    };

    /**
     * Abstract execution-driver interface for SEP.
     *
     * This is the boundary between:
     *
     *   existing project graph/activity/task state
     *                         +
     *                  SEP application
     *                         +
     *                  SEP execution policy
     *                         |
     *                         v
     *                  SEP execution driver
     *                         |
     *                         v
     *                 Phase 13 CUDA code
     *
     * The interface intentionally does not prescribe a graph container.
     *
     * This is important for our project because graph data, activity tracking,
     * partitions, and tasks already have their own abstractions. SEP should not
     * replace those abstractions with a monolithic GraphDatum object.
     *
     * The concrete Phase 13 implementation will eventually bind this interface
     * to the existing project graph representation and CUDA execution state.
     */
    template <typename TValue,
              typename TBuffer,
              typename TWeight = double>
    class SEPExecutionDriver
    {
    public:
        using application_type =
            SEPApplication<TValue, TBuffer, TWeight>;

        using execution_config_type = SEPExecutionConfig;

        using execution_variant_type = SEPExecutionVariant;

        using step_result_type = SEPExecutionResult;

        virtual ~SEPExecutionDriver() = default;

        /**
         * Prepare the driver for execution.
         *
         * Phase 12:
         *   This is an interface only.
         *
         * Phase 13:
         *   A concrete implementation may bind graph/device state, allocate
         *   device-side buffers, and prepare the selected execution variant.
         *
         * No transfer strategy is implied by this interface.
         */
        virtual void initialize(
            application_type &application,
            const execution_config_type &config) = 0;

        /**
         * Bind the existing project's graph/activity/partition/task/frontier state.
         *
         * Ownership remains with the caller.
         */
        virtual void set_context(
            SEPExecutionContext &context) = 0;

        /**
         * Execute one logical SEP step/round.
         *
         * The meaning of a step depends on the selected execution variant:
         *
         *   SYNC:
         *       one synchronization-delimited logical round.
         *
         *   ASYNC:
         *       one driver-defined unit of asynchronous progress.
         *
         *   PUSH/PULL:
         *       determines the direction in which application updates are
         *       propagated/consumed.
         *
         *   DATA_DRIVEN/TOPOLOGY_DRIVEN:
         *       determines whether work is selected from activity/worklist state
         *       or traversed from the topology domain.
         *
         * The actual implementation is deferred to Phase 13.
         */
        virtual step_result_type execute_step() = 0;

        /**
         * Return the execution policy currently bound to the driver.
         */
        virtual const execution_variant_type &
        execution_variant() const noexcept = 0;

        /**
         * Whether initialize() has successfully prepared the driver.
         */
        virtual bool initialized() const noexcept = 0;

        /**
         * Whether the current execution has reached its termination condition.
         */
        virtual bool converged() const noexcept = 0;

        /**
         * Release execution-specific state.
         *
         * This does not imply ownership of the project's graph representation.
         */
        virtual void finalize() noexcept = 0;
    };

} // namespace hytgraph::sep

#endif // HYTGRAPH_SEP_EXECUTION_DRIVER_HPP